### ISSUE TITLE
Can't install  @bearclaw/cel, @buf/cel_spec.bufbuild_es not found

### ISSUE THREAD

**Issue by rayokota** [jafaircl/bearclaw#37]
**Describe the bug**

```
% npm install @bearclaw/cel

npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@buf%2fcel_spec.bufbuild_es - Not found
npm error 404
npm error 404  '@buf/cel_spec.bufbuild_es@^2.1.0-20230602032904-0583f28ce7d3.1' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/robertyokota/.npm/_logs/2024-12-19T04_18_34_361Z-debug-0.log
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rayokota** [comment]
Also `[@buf/google_cel-spec.bufbuild_es](https://www.npmjs.com/package/%40buf%2Fgoogle_cel-spec.bufbuild_es)` is not public as well

**Comment by jafaircl** [comment]
You’ll need to configure your package manager to use the buf registry. This is documented [here](https://buf.build/google/cel-spec/sdks) but I should have added that to the readme.

For npm, the command is `npm config set @buf:registry https://buf.build/gen/npm/v1/`

After that, install should work
